In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

print("Imports completed successfully.")

Imports completed successfully.

# NBA MVP Predictor: Data Audit

## Objective
Explore the historical NBA MVP voting data before building a data-collection and machine-learning pipeline.

## Questions to answer
1. What columns are available in the MVP voting table?
2. Which seasons are present?
3. Is MVP voting available as a numeric modeling target?
4. Which features contain missing values?
5. What data-cleaning issues need to be addressed before modeling?

In [2]:
# Use one completed season for the initial data-collection test.
season_end_year = 2025

# Basketball Reference uses the ending calendar year in this URL.
url = f"https://www.basketball-reference.com/awards/awards_{season_end_year}.html"

# Read every HTML table available on the page.
tables = pd.read_html(url)

print(f"Number of tables found: {len(tables)}")

# Display the column names and first five rows from each table.
for i, table in enumerate(tables):
    print(f"\nTable {i}")
    print(table.columns.tolist())
    display(table.head())

Number of tables found: 5

Table 0
[('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]

  Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Rank                   Player                Age
0                  1  Shai Gilgeous-Alexander                 26
1                  2             Nikola Jokić                 29
2                  3    Giannis Antetokounmpo                 30
3                  4             Jayson Tatum                 26
4                  5         Donovan Mitchell                 28

  Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                  Tm  First Pts Won Pts Max  Share                  G
0                OKC     71     913    1000  0.913                 76
1                DEN     29     787    1000  0.787                 70
2                MIL      0     470    1000  0.470                 67
3                BOS      0     311    1000  0.311                 72
4                CLE      0      74    1000  0.074                 71

  Per Game                             Shooting               Advanced
        MP   PTS   TRB   AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0     34.2  32.7   5.0   6.4  1.7  1.0    0.519  0.375  0.898     16.7  0.309
1     36.7  29.6  12.7  10.2  1.8  0.6    0.576  0.417  0.800     16.4  0.307
2     34.2  30.4  11.9   6.5  0.9  1.2    0.601  0.222  0.617     11.5  0.241
3     36.4  26.8   8.7   6.0  1.1  0.5    0.452  0.343  0.814      9.5  0.174
4     31.4  24.0   4.5   5.0  1.3  0.2    0.443  0.368  0.823      7.6  0.163

Table 1
[('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]

  Unnamed: 0_level_0  Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Rank              Player                Age
0                  1      Stephon Castle                 20
1                  2  Zaccharie Risacher                 19
2                  3        Jaylen Wells                 21
3                  4           Alex Sarr                 19
4                  5           Zach Edey                 22

  Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                  Tm  First Pts Won Pts Max  Share                  G
0                SAS     92     482     500  0.964                 81
1                ATL      5     245     500  0.490                 75
2                MEM      3     123     500  0.246                 79
3                WAS      0      34     500  0.068                 67
4                MEM      0      10     500  0.020                 66

  Per Game                           Shooting               Advanced
        MP   PTS  TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0     26.7  14.7  3.7  4.1  0.9  0.3    0.428  0.285  0.724      1.1  0.025
1     24.6  12.6  3.6  1.2  0.7  0.5    0.458  0.355  0.711      1.8  0.046
2     25.9  10.4  3.4  1.7  0.6  0.1    0.425  0.352  0.822      3.5  0.083
3     27.1  13.0  6.5  2.4  0.7  1.5    0.394  0.308  0.679     -0.3 -0.007
4     21.5   9.2  8.3  1.0  0.5  1.3    0.580  0.346  0.709      4.9  0.165

Table 2
[('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Pos'), ('Unnamed: 2_level_0', 'Player'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Voting', '1st Tm'), ('Voting', '2nd Tm'), ('Voting', '3rd Tm'), ('Unnamed: 11_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]

  Unnamed: 0_level_0 Unnamed: 1_level_0       Unnamed: 2_level_0  \
                # Tm                Pos                   Player
0                NaN                NaN                      NaN
1                 1T                  F    Giannis Antetokounmpo
2                 1T                  G  Shai Gilgeous-Alexander
3                 1T                  C             Nikola Jokić
4                 1T                  F             Jayson Tatum

  Unnamed: 3_level_0 Unnamed: 4_level_0  Voting                              \
                 Age                 Tm Pts Won Pts Max Share 1st Tm 2nd Tm
0                NaN                NaN     NaN     NaN   NaN    NaN    NaN
1               30.0                MIL   500.0   500.0   1.0  100.0    0.0
2               26.0                OKC   500.0   500.0   1.0  100.0    0.0
3               29.0                DEN   500.0   500.0   1.0  100.0    0.0
4               26.0                BOS   500.0   500.0   1.0  100.0    0.0

         Unnamed: 11_level_0 Per Game                             Shooting  \
  3rd Tm                   G       MP   PTS   TRB   AST  STL  BLK      FG%
0    NaN                 NaN      NaN   NaN   NaN   NaN  NaN  NaN      NaN
1    0.0                67.0     34.2  30.4  11.9   6.5  0.9  1.2    0.601
2    0.0                76.0     34.2  32.7   5.0   6.4  1.7  1.0    0.519
3    0.0                70.0     36.7  29.6  12.7  10.2  1.8  0.6    0.576
4    0.0                72.0     36.4  26.8   8.7   6.0  1.1  0.5    0.452

                Advanced
     3P%    FT%       WS  WS/48
0    NaN    NaN      NaN    NaN
1  0.222  0.617     11.5  0.241
2  0.375  0.898     16.7  0.309
3  0.417  0.800     16.4  0.307
4  0.343  0.814      9.5  0.174

Table 3
[('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Pos'), ('Unnamed: 2_level_0', 'Player'), ('Unnamed: 3_level_0', 'Age'), ('Unnamed: 4_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48'), ('Advanced', 'DWS'), ('Advanced', 'DBPM'), ('Advanced', 'DRtg')]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                # Tm                Pos             Player                Age
0                1st                  F        Evan Mobley               23.0
1                1st                  G      Dyson Daniels               21.0
2                1st                  F      Luguentz Dort               25.0
3                1st                  F     Draymond Green               34.0
4                1st                  F      Amen Thompson               22.0

  Unnamed: 4_level_0  Voting                Unnamed: 8_level_0 Per Game        \
                  Tm Pts Won Pts Max  Share                  G       MP   PTS
0                CLE   199.0   200.0  0.995               71.0     30.5  18.5
1                ATL   191.0   200.0  0.955               76.0     33.8  14.1
2                OKC   180.0   200.0  0.900               71.0     29.2  10.1
3                GSW   179.0   200.0  0.895               68.0     29.2   9.0
4                HOU   171.0   200.0  0.855               69.0     32.2  14.1

                      Shooting               Advanced
   TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48  DWS DBPM   DRtg
0  9.3  3.2  0.9  1.6    0.557  0.370  0.725      9.0  0.200  3.8  1.5  108.0
1  5.9  4.4  3.0  0.7    0.493  0.340  0.593      5.0  0.093  3.7  2.6  111.0
2  4.1  1.6  1.1  0.5    0.435  0.412  0.717      5.6  0.129  3.2  0.8  110.0
3  6.1  5.6  1.5  1.0    0.424  0.325  0.687      3.7  0.088  3.4  2.8  109.0
4  8.2  3.8  1.4  1.3    0.557  0.275  0.684      8.0  0.172  3.9  2.6  108.0

Table 4
[('Unnamed: 0_level_0', '# Tm'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Voting', '1st Tm'), ('Voting', '2nd Tm'), ('Unnamed: 9_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]

  Unnamed: 0_level_0  Unnamed: 1_level_0 Unnamed: 2_level_0  \
                # Tm              Player                Age
0                1st      Stephon Castle               20.0
1                1st  Zaccharie Risacher               19.0
2                1st        Jaylen Wells               21.0
3                1st           Zach Edey               22.0
4                1st           Alex Sarr               19.0

  Unnamed: 3_level_0  Voting                              Unnamed: 9_level_0  \
                  Tm Pts Won Pts Max  Share 1st Tm 2nd Tm                  G
0                SAS   200.0   200.0  1.000  100.0    0.0               81.0
1                ATL   199.0   200.0  0.995   99.0    1.0               75.0
2                MEM   195.0   200.0  0.975   96.0    3.0               79.0
3                MEM   173.0   200.0  0.865   73.0   27.0               66.0
4                WAS   150.0   200.0  0.750   54.0   42.0               67.0

  Per Game                           Shooting               Advanced
        MP   PTS  TRB  AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0     26.7  14.7  3.7  4.1  0.9  0.3    0.428  0.285  0.724      1.1  0.025
1     24.6  12.6  3.6  1.2  0.7  0.5    0.458  0.355  0.711      1.8  0.046
2     25.9  10.4  3.4  1.7  0.6  0.1    0.425  0.352  0.822      3.5  0.083
3     21.5   9.2  8.3  1.0  0.5  1.3    0.580  0.346  0.709      4.9  0.165
4     27.1  13.0  6.5  2.4  0.7  1.5    0.394  0.308  0.679     -0.3 -0.007

In [3]:
# Select the MVP voting table from the list of page tables.
mvp_2025 = tables[0].copy()

# Inspect the structure and the first records.
display(mvp_2025.head())

print("Dataset shape:", mvp_2025.shape)

print("\nColumn names:")
print(mvp_2025.columns.tolist())

print("\nData types and non-null counts:")
mvp_2025.info()

  Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Rank                   Player                Age
0                  1  Shai Gilgeous-Alexander                 26
1                  2             Nikola Jokić                 29
2                  3    Giannis Antetokounmpo                 30
3                  4             Jayson Tatum                 26
4                  5         Donovan Mitchell                 28

  Unnamed: 3_level_0 Voting                        Unnamed: 8_level_0  \
                  Tm  First Pts Won Pts Max  Share                  G
0                OKC     71     913    1000  0.913                 76
1                DEN     29     787    1000  0.787                 70
2                MIL      0     470    1000  0.470                 67
3                BOS      0     311    1000  0.311                 72
4                CLE      0      74    1000  0.074                 71

  Per Game                             Shooting               Advanced
        MP   PTS   TRB   AST  STL  BLK      FG%    3P%    FT%       WS  WS/48
0     34.2  32.7   5.0   6.4  1.7  1.0    0.519  0.375  0.898     16.7  0.309
1     36.7  29.6  12.7  10.2  1.8  0.6    0.576  0.417  0.800     16.4  0.307
2     34.2  30.4  11.9   6.5  0.9  1.2    0.601  0.222  0.617     11.5  0.241
3     36.4  26.8   8.7   6.0  1.1  0.5    0.452  0.343  0.814      9.5  0.174
4     31.4  24.0   4.5   5.0  1.3  0.2    0.443  0.368  0.823      7.6  0.163

Dataset shape: (12, 20)

Column names:
[('Unnamed: 0_level_0', 'Rank'), ('Unnamed: 1_level_0', 'Player'), ('Unnamed: 2_level_0', 'Age'), ('Unnamed: 3_level_0', 'Tm'), ('Voting', 'First'), ('Voting', 'Pts Won'), ('Voting', 'Pts Max'), ('Voting', 'Share'), ('Unnamed: 8_level_0', 'G'), ('Per Game', 'MP'), ('Per Game', 'PTS'), ('Per Game', 'TRB'), ('Per Game', 'AST'), ('Per Game', 'STL'), ('Per Game', 'BLK'), ('Shooting', 'FG%'), ('Shooting', '3P%'), ('Shooting', 'FT%'), ('Advanced', 'WS'), ('Advanced', 'WS/48')]

Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   (Unnamed: 0_level_0, Rank)    12 non-null     object
 1   (Unnamed: 1_level_0, Player)  12 non-null     object
 2   (Unnamed: 2_level_0, Age)     12 non-null     int64
 3   (Unnamed: 3_level_0, Tm)      12 non-null     object
 4   (Voting, First)               12 non-null     int64
 5   (Voting, Pts Won)             12 non-null     int64
 6   (Voting, Pts Max)             12 non-null     int64
 7   (Voting, Share)               12 non-null     float64
 8   (Unnamed: 8_level_0, G)       12 non-null     int64
 9   (Per Game, MP)                12 non-null     float64
 10  (Per Game, PTS)               12 non-null     float64
 11  (Per Game, TRB)               12 non-null     float64
 12  (Per Game, AST)               12 non-null     float64
 13  (Per Game, STL)               12 non-null     float64
 14  (Per Game, BLK)               12 non-null     float64
 15  (Shooting, FG%)               12 non-null     float64
 16  (Shooting, 3P%)               12 non-null     float64
 17  (Shooting, FT%)               12 non-null     float64
 18  (Advanced, WS)                12 non-null     float64
 19  (Advanced, WS/48)             12 non-null     float64
dtypes: float64(12), int64(5), object(3)
memory usage: 2.0+ KB

In [4]:
# Count missing values in each column.
missing_values = (
    mvp_2025.isna()
    .sum()
    .sort_values(ascending=False)
)

# Show only columns that contain at least one missing value.
display(missing_values[missing_values > 0])

Series([], dtype: int64)

In [6]:
print(mvp_2025.columns)
print("\nColumn index type:")
print(type(mvp_2025.columns))

MultiIndex([('Unnamed: 0_level_0',    'Rank'),
            ('Unnamed: 1_level_0',  'Player'),
            ('Unnamed: 2_level_0',     'Age'),
            ('Unnamed: 3_level_0',      'Tm'),
            (            'Voting',   'First'),
            (            'Voting', 'Pts Won'),
            (            'Voting', 'Pts Max'),
            (            'Voting',   'Share'),
            ('Unnamed: 8_level_0',       'G'),
            (          'Per Game',      'MP'),
            (          'Per Game',     'PTS'),
            (          'Per Game',     'TRB'),
            (          'Per Game',     'AST'),
            (          'Per Game',     'STL'),
            (          'Per Game',     'BLK'),
            (          'Shooting',     'FG%'),
            (          'Shooting',     '3P%'),
            (          'Shooting',     'FT%'),
            (          'Advanced',      'WS'),
            (          'Advanced',   'WS/48')],
           )

Column index type:
<class 'pandas.core.indexes.multi.MultiIndex'>

In [7]:
# Convert two-level column labels into single, consistent names.
mvp_2025.columns = [
    second_level
    if first_level.startswith("Unnamed")
    else f"{first_level}_{second_level}"
    for first_level, second_level in mvp_2025.columns
]

# Standardize names for Python-friendly use.
mvp_2025.columns = (
    mvp_2025.columns
    .str.lower()
    .str.replace("%", "_pct", regex=False)
    .str.replace("/", "_per_", regex=False)
    .str.replace(" ", "_", regex=False)
)

print(mvp_2025.columns.tolist())
display(mvp_2025.head())

['rank', 'player', 'age', 'tm', 'voting_first', 'voting_pts_won', 'voting_pts_max', 'voting_share', 'g', 'per_game_mp', 'per_game_pts', 'per_game_trb', 'per_game_ast', 'per_game_stl', 'per_game_blk', 'shooting_fg_pct', 'shooting_3p_pct', 'shooting_ft_pct', 'advanced_ws', 'advanced_ws_per_48']

,rank,player,age,tm,voting_first,voting_pts_won,voting_pts_max,voting_share,g,per_game_mp,per_game_pts,per_game_trb,per_game_ast,per_game_stl,per_game_blk,shooting_fg_pct,shooting_3p_pct,shooting_ft_pct,advanced_ws,advanced_ws_per_48
0,1,Shai Gilgeous-Alexander,26,OKC,71,913,1000,0.913,76,34.2,32.7,5.0,6.4,1.7,1.0,0.519,0.375,0.898,16.7,0.309
1,2,Nikola Jokić,29,DEN,29,787,1000,0.787,70,36.7,29.6,12.7,10.2,1.8,0.6,0.576,0.417,0.800,16.4,0.307
2,3,Giannis Antetokounmpo,30,MIL,0,470,1000,0.470,67,34.2,30.4,11.9,6.5,0.9,1.2,0.601,0.222,0.617,11.5,0.241
3,4,Jayson Tatum,26,BOS,0,311,1000,0.311,72,36.4,26.8,8.7,6.0,1.1,0.5,0.452,0.343,0.814,9.5,0.174
4,5,Donovan Mitchell,28,CLE,0,74,1000,0.074,71,31.4,24.0,4.5,5.0,1.3,0.2,0.443,0.368,0.823,7.6,0.163

In [8]:
# Check duplicate records in this MVP-voting table.
duplicate_rows = mvp_2025.duplicated().sum()

# Check whether any player appears more than once in the same season.
duplicate_players = mvp_2025.duplicated(subset=["player"]).sum()

print(f"Exact duplicate rows: {duplicate_rows}")
print(f"Duplicate player names: {duplicate_players}")

# Review the distribution of numeric features.
display(mvp_2025.describe())

Exact duplicate rows: 0
Duplicate player names: 0

,age,voting_first,voting_pts_won,voting_pts_max,voting_share,g,per_game_mp,per_game_pts,per_game_trb,per_game_ast,per_game_stl,per_game_blk,shooting_fg_pct,shooting_3p_pct,shooting_ft_pct,advanced_ws,advanced_ws_per_48
count,12.000000,12.000000,12.000000,12.0,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.00000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,28.916667,8.333333,216.666667,1000.0,0.216667,71.666667,34.375000,26.116667,7.066667,6.758333,1.20000,0.691667,0.493583,0.362833,0.814167,9.766667,0.190333
std,5.517877,21.423578,332.107960,0.0,0.332108,4.313474,2.010032,3.760521,3.060402,2.037582,0.31334,0.418783,0.059949,0.048928,0.082269,3.428579,0.063332
min,23.000000,0.000000,1.000000,1000.0,0.001000,65.000000,30.500000,18.500000,2.900000,3.200000,0.90000,0.100000,0.410000,0.222000,0.617000,5.900000,0.115000
25%,25.250000,0.000000,1.750000,1000.0,0.001750,70.000000,33.700000,24.300000,4.875000,5.750000,0.97500,0.475000,0.447750,0.355000,0.795500,7.850000,0.149750
50%,28.000000,0.000000,14.000000,1000.0,0.014000,70.500000,34.950000,26.050000,5.950000,6.450000,1.10000,0.600000,0.478500,0.372500,0.822000,8.350000,0.170000
75%,31.250000,0.000000,350.750000,1000.0,0.350750,73.000000,35.625000,28.100000,8.850000,8.325000,1.35000,0.850000,0.528500,0.386000,0.853000,10.000000,0.210250
max,40.000000,71.000000,913.000000,1000.0,0.913000,79.000000,36.700000,32.700000,12.700000,10.200000,1.80000,1.600000,0.601000,0.417000,0.933000,16.700000,0.309000

In [9]:
# Display MVP candidates in descending order of vote share.
mvp_ranking = (
    mvp_2025[
        [
            "rank",
            "player",
            "tm",
            "voting_first",
            "voting_pts_won",
            "voting_pts_max",
            "voting_share",
            "per_game_pts",
            "per_game_trb",
            "per_game_ast",
            "advanced_ws",
            "advanced_ws_per_48",
        ]
    ]
    .sort_values("voting_share", ascending=False)
    .reset_index(drop=True)
)

display(mvp_ranking)

# Validate the voting-share range.
print("Minimum voting share:", mvp_2025["voting_share"].min())
print("Maximum voting share:", mvp_2025["voting_share"].max())
print("Total voting share:", mvp_2025["voting_share"].sum())

,rank,player,tm,voting_first,voting_pts_won,voting_pts_max,voting_share,per_game_pts,per_game_trb,per_game_ast,advanced_ws,advanced_ws_per_48
0,1,Shai Gilgeous-Alexander,OKC,71,913,1000,0.913,32.7,5.0,6.4,16.7,0.309
1,2,Nikola Jokić,DEN,29,787,1000,0.787,29.6,12.7,10.2,16.4,0.307
2,3,Giannis Antetokounmpo,MIL,0,470,1000,0.470,30.4,11.9,6.5,11.5,0.241
3,4,Jayson Tatum,BOS,0,311,1000,0.311,26.8,8.7,6.0,9.5,0.174
4,5,Donovan Mitchell,CLE,0,74,1000,0.074,24.0,4.5,5.0,7.6,0.163
5,6,LeBron James,LAL,0,16,1000,0.016,24.4,7.8,8.2,7.7,0.152
6,7T,Cade Cunningham,DET,0,12,1000,0.012,26.1,6.1,9.1,5.9,0.115
7,7T,Anthony Edwards,MIN,0,12,1000,0.012,27.6,5.7,4.5,8.4,0.140
8,9,Stephen Curry,GSW,0,2,1000,0.002,24.5,4.4,6.0,7.9,0.168
9,10T,Jalen Brunson,NYK,0,1,1000,0.001,26.0,2.9,7.3,8.3,0.172
10,10T,James Harden,LAC,0,1,1000,0.001,22.8,5.8,8.7,8.3,0.143
11,10T,Evan Mobley,CLE,0,1,1000,0.001,18.5,9.3,3.2,9.0,0.200

Minimum voting share: 0.001
Maximum voting share: 0.913
Total voting share: 2.599999999999999